### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by ericmorand** [NightlyCommit/stromboli#60]
- [x] Add accessors and set properties as `readonly private`
- [x] Make Source generic (it should be able to hold any kind of data)
- [x] Have Error belonging to a Source instead of a file path
- [x] Have dependencies instance of Source instead of string
